### PR TITLE
Fix README and CHANGES encoding errors.

### PR DESCRIPTION
**Pull request by bchatelard**

### CODE REVIEW

**Comment by kdeldycke** [comment]
@bchatelard : can you provide a stack trace for reference ?

**Comment by bchatelard** [comment]
Here is the stacktrace:

```
Downloading https://pypi.pv.ocshq.com/repository/24914/postal-address-0.7.1.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/sl/ltpf6scj7rjf88y52ppdf7h40000gn/T/pip-build-6a3tj001/postal-address/setup.py", line 52, in <module>
        long_description=get_long_description(),
      File "/var/folders/sl/ltpf6scj7rjf88y52ppdf7h40000gn/T/pip-build-6a3tj001/postal-address/setup.py", line 45, in get_long_description
        return open(readme).read() + '\n' + open(changes).read()
      File "/Users/bastien/ocs/ocs-object_store-world_backend/.tox/py34/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1368: ordinal not in range(128)
```

**Comment by kdeldycke** [comment]
Again, for reference, when I discussed this issue with @bchatelard this morning, it seems to be similar to https://github.com/crsmithdev/arrow/issues/202 in Python 3 environments.

I'm going to merge this PR and release a new version of the package based on good faith, even if we have found no way to reproduce the issue in Travis jobs.

**Comment by kdeldycke** [comment]
Thanks @bchatelard for the traceback ! :)

**Pull request merged**
